name: CI Pipeline

on:
  pull_request:

jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2
        env:
          GO111MODULE: "on"

      - name: Install dependencies
        run: make deps

      - name: Run linter
        run: make lint

      - name: Build application
        run: make build

      - name: Run tests
        run: make test
